networks:
  oscar_bookstore:
    driver: bridge
  mysql:
    external: true

services:
  nginx_be:
    image: nginx:alpine
    container_name: nginx_oscarbook_be
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./be-web-online-bookstore:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - oscar_bookstore

  php:
    image: vixiloc/php-mysql-composer
    container_name: php_oscarbook
    restart: unless-stopped
    tty: true
    volumes:
      - ./be-web-online-bookstore:/var/www/app
    networks:
      - oscar_bookstore
      - mysql

  vue:
    image: farrela46/fe-oscar:latest
    container_name: vue_oscarbook
    restart: unless-stopped
    tty: true
    volumes:
      - ./fe-vue-oscar-bookstore:/var/www/app
    ports:
      - "8080:80"
    networks:
      - oscar_bookstore